### ISSUE TITLE
Make built version more discoverable

### ISSUE THREAD

**Issue by chrysn** [textiles-lab/knitout-live-visualizer#20]
The built version at https://textiles-lab.github.io/knitout-live-visualizer/ (and on <https://textiles-lab.github.io/knitout-live-visualizer/simplified-visualizer.html>) is hard to discover -- I only found it because I guessed it might just be built using GitHub pages.

For better discoverability, I'd suggest linking to it from https://textiles-lab.github.io/publications/2020-knitout-visualizer/ (probably between Video Walkthrough and Get the Code), and from the README itself (possibly replacing the Installation section and first line of Usage to with a "There is an online version available at ...", and slimming down the installation using the `--recursive` flag to

> ## Local installation
>
> If you want to get an own copy of the Knitout Visualizer, e.g. to alter its code, type this on your command line:
>
> ```
> git clone --recursive https://github.com/textiles-lab/knitout-live-visualizer
> ```
>
> See the github documentation on cloning a repository if you need assistance with installation.

).

**Comment by ixchow** [comment]
And links are now live at: https://textiles-lab.github.io/publications/2020-knitout-visualizer/

Thanks for the suggestions! We probably shouldn't have taken two years to get to it.
